import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'database.dart';

/// The bundled exercise catalogue, generated by `tool/build_exercise_seed.dart`
/// from free-exercise-db and shipped as an asset. Nothing is downloaded at
/// runtime.
const String kExerciseSeedAsset = 'assets/data/exercises.json';

/// Bumped whenever the bundled catalogue is corrected in a way that has to
/// reach databases that were seeded before the correction.
///
/// 1: exercises you hold still - the plank, the side bridge, the isometric
///    neck work - were typed as body-weight exercises and so asked for
///    kilograms and repetitions. A hold has neither; it is a number of
///    seconds.
const int kSeedVersion = 1;

class ExerciseSeeder {
  const ExerciseSeeder(this.db);

  final AppDatabase db;

  /// Imports the catalogue on first start.
  ///
  /// Guarded by `app_settings.exercises_seeded`, so it can be called on every
  /// launch and only ever runs once. The whole import is one transaction: a
  /// half-seeded catalogue is worse than none.
  Future<int> seedIfNeeded({String assetKey = kExerciseSeedAsset}) async {
    final settings = await db.settingsDao.ensureInitialized();
    if (settings.exercisesSeeded) return 0;

    final raw = await rootBundle.loadString(assetKey);
    final inserted = await seedFromJson(raw);

    await db.settingsDao.updateSettings(
      const AppSettingsTableCompanion(
        exercisesSeeded: Value(true),
        // Freshly imported, so it is already the newest catalogue.
        seedVersion: Value(kSeedVersion),
      ),
    );
    return inserted;
  }

  /// Brings an already-seeded catalogue up to [kSeedVersion].
  ///
  /// Only the exercise *type* is rewritten, and only for exercises that came
  /// from the catalogue and whose type the user has not set themselves. That
  /// is the one field a correction has ever needed, and keeping the pass that
  /// narrow means it cannot touch a name, an instruction, a picture, anything
  /// the user made, or a choice the user has made.
  ///
  /// Returns how many exercises were re-typed.
  Future<int> refreshIfNeeded({String assetKey = kExerciseSeedAsset}) async {
    final settings = await db.settingsDao.ensureInitialized();
    if (!settings.exercisesSeeded) return 0;
    if (settings.seedVersion >= kSeedVersion) return 0;

    final raw = await rootBundle.loadString(assetKey);
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final list = (decoded['exercises'] as List).cast<Map<String, dynamic>>();

    final existing = {
      for (final row in await db.exercisesDao.getExercises(
        const ExerciseFilter(includeArchived: true),
      ))
        row.id: row,
    };

    var changed = 0;
    await db.transaction(() async {
      for (final entry in list) {
        final id = entry['id'] as String;
        final category = entry['category'] as String;
        final row = existing[id];
        // Not one of ours, already right, or the user has said themselves
        // how this exercise is done - all three mean: leave it.
        if (row == null ||
            row.isCustom ||
            row.categoryOverridden ||
            row.category == category) {
          continue;
        }
        await db.exercisesDao.updateExercise(
          id,
          ExercisesTableCompanion(category: Value(category)),
        );
        changed++;
      }
      await db.settingsDao.updateSettings(
        const AppSettingsTableCompanion(seedVersion: Value(kSeedVersion)),
      );
    });
    return changed;
  }

  /// Parses [raw] and writes every exercise. Exposed for tests and for the
  /// restore flow, which reseeds into a fresh database.
  Future<int> seedFromJson(String raw) async {
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final list = (decoded['exercises'] as List).cast<Map<String, dynamic>>();
    final now = DateTime.now().millisecondsSinceEpoch;

    final rows = list
        .map(
          (e) => ExercisesTableCompanion.insert(
            id: e['id'] as String,
            name: e['name'] as String,
            primaryMuscle: e['primary_muscle'] as String,
            secondaryMuscles: Value(
              jsonEncode((e['secondary_muscles'] as List?) ?? const []),
            ),
            equipment: Value(e['equipment'] as String?),
            category: e['category'] as String,
            instructions: Value(e['instructions'] as String?),
            createdAt: now,
          ),
        )
        .toList(growable: false);

    await db.transaction(() async {
      await db.exercisesDao.insertSeed(rows);
    });
    return rows.length;
  }
}
