import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'database.dart';

/// The bundled exercise catalogue, generated by `tool/build_exercise_seed.dart`
/// from free-exercise-db and shipped as an asset. Nothing is downloaded at
/// runtime.
const String kExerciseSeedAsset = 'assets/data/exercises.json';

class ExerciseSeeder {
  const ExerciseSeeder(this.db);

  final AppDatabase db;

  /// Imports the catalogue on first start.
  ///
  /// Guarded by `app_settings.exercises_seeded`, so it can be called on every
  /// launch and only ever runs once. The whole import is one transaction: a
  /// half-seeded catalogue is worse than none.
  Future<int> seedIfNeeded({String assetKey = kExerciseSeedAsset}) async {
    final settings = await db.settingsDao.ensureInitialized();
    if (settings.exercisesSeeded) return 0;

    final raw = await rootBundle.loadString(assetKey);
    final inserted = await seedFromJson(raw);

    await db.settingsDao.updateSettings(
      const AppSettingsTableCompanion(exercisesSeeded: Value(true)),
    );
    return inserted;
  }

  /// Parses [raw] and writes every exercise. Exposed for tests and for the
  /// restore flow, which reseeds into a fresh database.
  Future<int> seedFromJson(String raw) async {
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final list = (decoded['exercises'] as List).cast<Map<String, dynamic>>();
    final now = DateTime.now().millisecondsSinceEpoch;

    final rows = list
        .map(
          (e) => ExercisesTableCompanion.insert(
            id: e['id'] as String,
            name: e['name'] as String,
            primaryMuscle: e['primary_muscle'] as String,
            secondaryMuscles: Value(
              jsonEncode((e['secondary_muscles'] as List?) ?? const []),
            ),
            equipment: Value(e['equipment'] as String?),
            category: e['category'] as String,
            instructions: Value(e['instructions'] as String?),
            createdAt: now,
          ),
        )
        .toList(growable: false);

    await db.transaction(() async {
      await db.exercisesDao.insertSeed(rows);
    });
    return rows.length;
  }
}
