import 'dart:io';

import 'package:drift/native.dart';
import 'package:fitlog/core/db/database.dart';
import 'package:fitlog/core/db/seeder.dart';
import 'package:fitlog/core/widgets/exercise_image.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

/// The illustrations are generated by `tool/build_exercise_images.dart`. This
/// guards the contract between that tool and the app: every seeded exercise is
/// either accounted for in the manifest or explicitly marked as having no
/// picture, and every asset the manifest promises actually loads. A silent 404
/// in the UI is exactly what this is here to prevent.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late ExerciseImageManifest manifest;
  late List<ExerciseRow> exercises;
  late AppDatabase db;

  setUpAll(() async {
    manifest = await ExerciseImageManifest.load();
    db = AppDatabase(NativeDatabase.memory());
    await ExerciseSeeder(db).seedIfNeeded();
    exercises = await db.exercisesDao.getExercises();
  });

  tearDownAll(() async => db.close());

  test('the manifest was generated', () {
    expect(
      manifest.animated.isNotEmpty || manifest.staticOnly.isNotEmpty,
      isTrue,
      reason:
          'assets/exercises/manifest.json ontbreekt of is leeg. Draai '
          'tool/build_exercise_images.dart.',
    );
    expect(manifest.format, anyOf('webp', 'gif'));
  });

  test('every seeded exercise is accounted for', () {
    final known = {
      ...manifest.animated,
      ...manifest.staticOnly,
      ...manifest.withoutImages,
    };

    final unaccounted = [
      for (final exercise in exercises)
        if (!known.contains(exercise.id)) exercise.name,
    ];

    expect(
      unaccounted,
      isEmpty,
      reason:
          '${unaccounted.length} oefeningen staan noch in de manifest-lijsten '
          'noch als bewust zonder beeld gemarkeerd.',
    );
  });

  test('the manifest never claims an exercise the seed does not have', () {
    final seeded = {for (final e in exercises) e.id};
    for (final id in {...manifest.animated, ...manifest.staticOnly}) {
      expect(seeded, contains(id), reason: 'onbekend id in manifest: $id');
    }
  });

  test('most exercises have a two-frame animation', () {
    expect(manifest.animated.length, greaterThan(800));
  });

  test('every promised asset actually loads', () async {
    // Loading all 1750 assets is slow; a spread-out sample catches a broken
    // naming convention just as well as the full set would.
    final ids = manifest.animated.toList()..sort();
    final sample = [
      for (var i = 0; i < ids.length; i += (ids.length / 40).ceil()) ids[i],
    ];

    for (final id in sample) {
      for (final asset in [manifest.assetFor(id), manifest.thumbFor(id)]) {
        final bytes = await rootBundle.load(asset);
        expect(bytes.lengthInBytes, greaterThan(0), reason: asset);
      }
    }
  });

  test('an exercise without a picture has no asset promised', () {
    for (final id in manifest.withoutImages) {
      expect(manifest.hasImage(id), isFalse);
      expect(manifest.isAnimated(id), isFalse);
    }
  });

  test('the asset directory stays inside its budget', () async {
    // Summed on disk rather than through rootBundle: pulling 1750 assets into
    // the caching bundle just to weigh them exhausts the test isolate, and the
    // committed bytes are what ships anyway.
    final dir = Directory(kExerciseAssetDir);
    expect(await dir.exists(), isTrue);

    var total = 0;
    var files = 0;
    await for (final entity in dir.list()) {
      if (entity is! File) continue;
      total += await entity.length();
      files++;
    }

    expect(files, greaterThan(1000));

    const budget = 35 * 1024 * 1024;
    expect(
      total,
      lessThan(budget),
      reason: '${(total / 1048576).toStringAsFixed(1)} MB aan illustraties',
    );
  });
}
